# Generated by Django 5.1.5 on 2026-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfd',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mfdt',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
