# Generated by Django 5.1.5 on 2026-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mfd_description_mfdt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
