# Generated by Django 5.1.5 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_news_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='parks',
            name='button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
