# Generated by Django 5.1.5 on 2026-05-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_concertandevents_familyshows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Mfd',
        ),
    ]
