# Generated by Django 5.1.5 on 2026-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rarity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
