# Generated by Django 5.1.5 on 2026-05-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
